"""
models/alerts.py
Sends email alerts when:
  - Any SKU reaches CRITICAL status
  - Non-buyability % for LARGE items exceeds threshold in any category
  - Scheduled daily summary report (weekdays 08:00)
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date
from typing import Optional

import pandas as pd

from etl.db import load_config

logger = logging.getLogger(__name__)


def _build_html_table(df: pd.DataFrame, max_rows: int = 20) -> str:
    """Convert a DataFrame to a clean HTML table."""
    styles = """
    <style>
    table { border-collapse:collapse; font-family:Arial,sans-serif; font-size:13px; width:100%; }
    th { background:#1a3c5e; color:#fff; padding:8px 12px; text-align:left; }
    td { padding:7px 12px; border-bottom:1px solid #e0e0e0; }
    tr:nth-child(even) td { background:#f5f7fa; }
    .critical { color:#c0392b; font-weight:bold; }
    .reorder  { color:#e67e22; font-weight:bold; }
    .plan     { color:#2980b9; }
    .healthy  { color:#27ae60; }
    .alert    { color:#c0392b; font-weight:bold; }
    </style>
    """
    head = "<tr>" + "".join(f"<th>{c}</th>" for c in df.columns) + "</tr>"
    rows = []
    for _, row in df.head(max_rows).iterrows():
        cells = []
        for col, val in row.items():
            css = ""
            if col == "planning_status":
                css = {"CRITICAL":"critical","REORDER_NOW":"reorder",
                       "PLAN_REORDER":"plan","HEALTHY":"healthy"}.get(str(val),"")
            if col == "is_alert" and val is True:
                css = "alert"
                val = "⚠ YES"
            cells.append(f'<td class="{css}">{val}</td>')
        rows.append("<tr>" + "".join(cells) + "</tr>")
    return styles + f"<table>{head}{''.join(rows)}</table>"


def _send_email(subject: str, html_body: str, cfg: dict) -> bool:
    """Send HTML email via SMTP. Returns True on success."""
    if not cfg.get("smtp_host") or not cfg.get("recipients"):
        logger.warning("Email not configured — skipping send")
        return False

    recipients = [r.strip() for r in cfg["recipients"].split(",") if r.strip()]
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{cfg.get('subject_prefix','[Inventory]')} {subject}"
    msg["From"]    = cfg.get("from_address", "noreply@inventory")
    msg["To"]      = ", ".join(recipients)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(cfg["smtp_host"], int(cfg.get("smtp_port", 587))) as server:
            server.starttls()
            if cfg.get("smtp_user") and cfg.get("smtp_password"):
                server.login(cfg["smtp_user"], cfg["smtp_password"])
            server.sendmail(msg["From"], recipients, msg.as_string())
        logger.info("Email sent: %s → %s", subject, recipients)
        return True
    except Exception as e:
        logger.error("Email failed: %s", e)
        return False


def send_critical_alert(planning_df: pd.DataFrame) -> bool:
    """Alert immediately if any SKU is CRITICAL."""
    cfg = load_config()["alerts"]
    if not cfg.get("enabled", True):
        return False

    critical = planning_df[planning_df["planning_status"] == "CRITICAL"].copy()
    if critical.empty:
        return False

    cols = ["sku","product_name","category","size_class",
            "qty_available","avg_daily_units","coverage_days","suggested_order_qty"]
    critical = critical[[c for c in cols if c in critical.columns]]
    table_html = _build_html_table(critical)

    body = f"""
    <h2 style="color:#c0392b">⚠ Critical Inventory Alert — {date.today()}</h2>
    <p><strong>{len(critical)} SKU(s)</strong> have zero available stock and active demand.</p>
    {table_html}
    <p style="color:#666;font-size:12px">Generated by Inventory Planning Pipeline</p>
    """
    return _send_email(f"CRITICAL: {len(critical)} SKUs out of stock", body, cfg)


def send_non_buyability_alert(non_buy_df: pd.DataFrame) -> bool:
    """Alert if any LARGE category breaches the non-buyability threshold."""
    cfg = load_config()["alerts"]
    if not cfg.get("enabled", True):
        return False

    alerts = non_buy_df[non_buy_df["is_alert"] == True].copy()
    if alerts.empty:
        return False

    cols = ["category","total_skus","non_buyable_skus","non_buyability_pct","is_alert"]
    alerts = alerts[[c for c in cols if c in alerts.columns]]
    table_html = _build_html_table(alerts)

    threshold = float(load_config()["pipeline"]["non_buy_alert_threshold"]) * 100
    body = f"""
    <h2 style="color:#e67e22">⚠ Large Item Non-Buyability Alert — {date.today()}</h2>
    <p>{len(alerts)} category(ies) have exceeded the <strong>{threshold:.0f}%</strong>
       non-buyability threshold for <strong>LARGE</strong> items.</p>
    {table_html}
    <p style="color:#666;font-size:12px">Generated by Inventory Planning Pipeline</p>
    """
    return _send_email(f"Non-buyability alert: {len(alerts)} LARGE categories", body, cfg)


def send_daily_summary(kpis: dict, planning_df: pd.DataFrame, non_buy_df: pd.DataFrame) -> bool:
    """Daily morning summary email (weekdays 08:00)."""
    cfg = load_config()["alerts"]
    if not cfg.get("enabled", True):
        return False

    # Top items needing attention
    attention = planning_df[
        planning_df["planning_status"].isin(["CRITICAL","REORDER_NOW","PLAN_REORDER"])
    ].head(15).copy()
    cols = ["sku","product_name","category","size_class","planning_status",
            "qty_available","avg_daily_units","coverage_days","suggested_order_qty"]
    attention = attention[[c for c in cols if c in attention.columns]]

    non_buy_display = non_buy_df[
        ["category","total_skus","non_buyable_skus","non_buyability_pct","is_alert"]
    ].copy() if not non_buy_df.empty else pd.DataFrame()

    body = f"""
    <h2 style="color:#1a3c5e">📦 Daily Inventory Planning Report — {date.today()}</h2>

    <h3>KPI Summary</h3>
    <table style="border-collapse:collapse;font-size:13px">
    {''.join(f'<tr><td style="padding:5px 16px 5px 0;color:#555">{k.replace("_"," ").title()}</td><td style="padding:5px 0;font-weight:bold">{v}</td></tr>' for k,v in kpis.items() if not k.startswith("_"))}
    </table>

    <h3>Items Requiring Attention</h3>
    {_build_html_table(attention) if not attention.empty else '<p>✅ No items require immediate action.</p>'}

    <h3>Large Item Non-Buyability by Category</h3>
    {_build_html_table(non_buy_display) if not non_buy_display.empty else '<p>No LARGE inventory data.</p>'}

    <p style="color:#666;font-size:12px;margin-top:24px">
    Generated by Inventory Planning Pipeline · {date.today()}
    </p>
    """
    return _send_email(
        f"Daily Inventory Report — {kpis.get('critical_skus',0)} critical, "
        f"{kpis.get('reorder_now_skus',0)} reorder now",
        body, cfg
    )
